export const APPROVED_SOURCES = [
  { domain: "abcnews.go.com", label: "ABC News (US)" },
  { domain: "abc.net.au", label: "ABC News (AU)" },
  { domain: "aljazeera.com", label: "Al Jazeera" },
  { domain: "apnews.com", label: "AP News" },
  { domain: "arstechnica.com", label: "Ars Technica" },
  { domain: "afr.com", label: "Australian Financial Review" },
  { domain: "axios.com", label: "Axios" },
  { domain: "bbc.co.uk", label: "BBC News (UK)" },
  { domain: "bbc.com", label: "BBC News" },
  { domain: "bleacherreport.com", label: "Bleacher Report" },
  { domain: "bloomberg.com", label: "Bloomberg" },
  { domain: "breitbart.com", label: "Breitbart" },
  { domain: "businessinsider.com", label: "Business Insider" },
  { domain: "buzzfeed.com", label: "BuzzFeed" },
  { domain: "cbc.ca", label: "CBC News" },
  { domain: "cbsnews.com", label: "CBS News" },
  { domain: "cnn.com", label: "CNN" },
  { domain: "engadget.com", label: "Engadget" },
  { domain: "financialpost.com", label: "Financial Post" },
  { domain: "fortune.com", label: "Fortune" },
  { domain: "foxnews.com", label: "Fox News" },
  { domain: "independent.co.uk", label: "The Independent" },
  { domain: "mashable.com", label: "Mashable" },
  { domain: "nationalgeographic.com", label: "National Geographic" },
  { domain: "nbcnews.com", label: "NBC News" },
  { domain: "newsweek.com", label: "Newsweek" },
  { domain: "politico.com", label: "Politico" },
  { domain: "techcrunch.com", label: "TechCrunch" },
  { domain: "techradar.com", label: "TechRadar" },
  { domain: "theglobeandmail.com", label: "The Globe and Mail" },
  { domain: "thehill.com", label: "The Hill" },
  { domain: "theverge.com", label: "The Verge" },
  { domain: "time.com", label: "Time" },
  { domain: "usatoday.com", label: "USA Today" },
  { domain: "washingtonpost.com", label: "Washington Post" },
  { domain: "wired.com", label: "Wired" },
  { domain: "wsj.com", label: "Wall Street Journal" },
];
